"""
make_demo_pdf.py — Build a 5-page demo PDF for screenshot capture.

Produces ``docs/screenshots/_assets/demo.pdf`` with content designed to be
visible in feature screenshots:

  Page 1 — Title page (large heading, subtitle, footer)
  Page 2 — Body text (3 paragraphs + a styled section header)
  Page 3 — Embedded image (an 800x500 PNG rendered into the page)
  Page 4 — Multi-page TOC mock (so the outline sidebar isn't empty)
  Page 5 — Wide-aspect table (so ``rotate`` produces a visible change)

Run from the project root:
    source .venv/bin/activate
    python tests/make_demo_pdf.py

The script is idempotent: rerun any time to refresh the fixture.
"""
from __future__ import annotations

import io
import json
import sys
from pathlib import Path

import fitz  # PyMuPDF
from PIL import Image as PILImage

PROJECT_ROOT = Path(__file__).resolve().parents[1]
ASSET_DIR = PROJECT_ROOT / "docs" / "screenshots" / "_assets"
OUT_PDF = ASSET_DIR / "demo.pdf"
MANIFEST = ASSET_DIR / "manifest.json"

# Use Helvetica core fonts so the script doesn't depend on
# any external TTF (these are always available in PyMuPDF).
FONT_REG = "helv"
FONT_BOLD = "hebo"
FONT_OBL = "heit"


def _add_outline(doc: fitz.Document, page: int, title: str, level: int = 1) -> None:
    """Append a top-level (or nested) outline entry pointing at ``page``."""
    # fitz's outline API takes a list of [level, title, page (1-based), ...].
    # We just call ``set_toc`` once after building all pages.
    pass  # handled in build()


def _make_image_png() -> bytes:
    """Render a brightly-coloured 800x500 test image in-memory and return PNG bytes."""
    img = PILImage.new("RGB", (800, 500), (24, 24, 36))
    px = img.load()
    # 4 colour stripes top→bottom.
    stripes = [(255, 99, 132), (54, 162, 235), (255, 206, 86), (75, 192, 130)]
    band_h = 500 // 4
    for i, colour in enumerate(stripes):
        for y in range(i * band_h, (i + 1) * band_h):
            for x in range(800):
                # Diagonal gradient for some texture.
                px[x, y] = tuple(max(0, min(255, c + (x + y) // 8 - 50))
                                 for c in colour)
    buf = io.BytesIO()
    img.save(buf, format="PNG")
    return buf.getvalue()


def build() -> fitz.Document:
    """Build the demo document and return the open fitz.Document."""
    doc = fitz.open()
    page_w, page_h = 595, 842  # A4 portrait in points

    # ---- Page 1: Title ----------------------------------------------------
    p = doc.new_page(width=page_w, height=page_h)
    p.insert_text((page_w / 2 - 130, 200), "TermiPDF",
                  fontname="hebo", fontsize=42, color=(0.8, 0.65, 1.0))
    p.insert_text((page_w / 2 - 100, 240), "Feature Demo",
                  fontname="helv", fontsize=22, color=(0.85, 0.85, 0.95))
    p.insert_text((50, 320),
                  "This document exercises every feature visible in the "
                  "README's screenshot gallery: highlighting, ink, text",
                  fontname="helv", fontsize=11, color=(0.6, 0.6, 0.7))
    p.insert_text((50, 340),
                  "insertion, QR codes, drag-drop page reordering, page",
                  fontname="helv", fontsize=11, color=(0.6, 0.6, 0.7))
    p.insert_text((50, 360),
                  "rotation, image → PDF, and the embedded terminal.",
                  fontname="helv", fontsize=11, color=(0.6, 0.6, 0.7))
    # Decorative accent block.
    p.draw_rect(fitz.Rect(50, page_h - 60, page_w - 100, 4),
                color=(0.8, 0.65, 1.0), fill=(0.8, 0.65, 1.0), width=0)
    p.insert_text((50, page_h - 25),
                  "Generated by tests/make_demo_pdf.py",
                  fontname="heit", fontsize=9, color=(0.5, 0.5, 0.6))

    # ---- Page 2: Body text ------------------------------------------------
    p = doc.new_page(width=page_w, height=page_h)
    p.insert_text((50, 70), "Chapter 1 — Overview",
                  fontname="hebo", fontsize=22, color=(0.85, 0.85, 0.95))
    paragraphs = [
        ("TermiPDF combines a modern PDF editor with an embedded "
         "command-line terminal. Every action — opening files, "
         "switching modes, swapping pages, generating QR codes — is "
         "both a GUI button and a typed command, so power users never "
         "have to leave the keyboard."),
        ("Annotations are written into the PDF as standard types "
         "(Ink, Highlight, FreeText), so a TermiPDF-edited document "
         "displays identically in Chrome, Edge, Acrobat, and Preview. "
         "There is no proprietary sidecar; one file in, one file out."),
        ("The terminal drives everything. Type ``help`` at the bottom "
         "of the window to see the full command reference. Press Ctrl+L "
         "to focus the input box, Ctrl+Z to undo the last annotation "
         "or page operation, and Ctrl+Y to redo."),
    ]
    y = 130
    for para in paragraphs:
        # Naive line wrap at ~80 chars / line.
        words = para.split()
        lines, cur = [], ""
        for w in words:
            if len(cur) + 1 + len(w) > 80:
                lines.append(cur)
                cur = w
            else:
                cur = (cur + " " + w).strip()
        if cur:
            lines.append(cur)
        for line in lines:
            p.insert_text((50, y), line, fontname="helv", fontsize=11,
                          color=(0.85, 0.85, 0.95))
            y += 18
        y += 12

    # ---- Page 3: Embedded image -------------------------------------------
    p = doc.new_page(width=page_w, height=page_h)
    p.insert_text((50, 70), "Chapter 2 — Embedded Image",
                  fontname="hebo", fontsize=22, color=(0.85, 0.85, 0.95))
    p.insert_text((50, 100),
                  "The image below was inserted via fitz.insert_image(); "
                  "it round-trips through the doc unchanged.",
                  fontname="helv", fontsize=11, color=(0.7, 0.7, 0.8))
    img_bytes = _make_image_png()
    # Save to a temp file because insert_image takes a filename/path.
    import tempfile
    with tempfile.NamedTemporaryFile(suffix=".png", delete=False) as tmp:
        tmp.write(img_bytes)
        tmp_path = tmp.name
    try:
        img_rect = fitz.Rect(50, 140, page_w - 50, 140 + (500 * (page_w - 100) / 800))
        p.insert_image(img_rect, filename=tmp_path)
    finally:
        import os
        try:
            os.remove(tmp_path)
        except OSError:
            pass

    # ---- Page 4: TOC mock --------------------------------------------------
    p = doc.new_page(width=page_w, height=page_h)
    p.insert_text((50, 70), "Chapter 3 — Contents",
                  fontname="hebo", fontsize=22, color=(0.85, 0.85, 0.95))
    # 2-column body text on this page so the outline sidebar (which lists
    # the headings below) has real entries to show.
    left_paras = [
        ("Section A", 13, (0.85, 0.65, 1.0)),
        ("This is a paragraph spanning the left half of page 4. "
         "Its purpose is to fill the left column with readable "
         "content so the outline sidebar has something to render "
         "besides the headings. The headings below also appear in "
         "the TOC of the demo PDF and so should appear in the "
         "left-rail outline of the viewer.", 11, (0.85, 0.85, 0.95)),
        ("", 0, (0, 0, 0)),
        ("Subsection A.1", 12, (0.54, 0.71, 0.98)),
        ("More body copy on the left column. Each of these "
         "headings emits an outline entry.", 11, (0.85, 0.85, 0.95)),
    ]
    right_paras = [
        ("Section B", 13, (0.85, 0.65, 1.0)),
        ("This is the right column. Identical structure, "
         "different heading for visual variety. The outline "
         "panel groups these under the chapter hierarchy, so "
         "they appear as expandable nodes under 'Chapter 3'.", 11,
         (0.85, 0.85, 0.95)),
        ("", 0, (0, 0, 0)),
        ("Subsection B.1", 12, (0.54, 0.71, 0.98)),
        ("And another right-column body paragraph to round out "
         "the page.", 11, (0.85, 0.85, 0.95)),
    ]
    for col, paras in (("left", left_paras), ("right", right_paras)):
        x = 50 if col == "left" else (page_w / 2 + 10)
        y = 130
        for text, size, color in paras:
            if not text:
                y += 12
                continue
            p.insert_text((x, y), text,
                          fontname="hebo" if size >= 12 and "Section" in text or
                          "Subsection" in text else FONT_REG,
                          fontsize=size, color=color)
            y += size + 8

    # ---- Page 5: Wide-aspect table ----------------------------------------
    p = doc.new_page(width=page_w, height=page_h)
    p.insert_text((50, 70), "Chapter 4 — Sample Table",
                  fontname="hebo", fontsize=22, color=(0.85, 0.85, 0.95))
    p.insert_text((50, 100),
                  "A wide table rendered across the full page width.",
                  fontname="helv", fontsize=11, color=(0.7, 0.7, 0.8))
    # Hand-rolled grid (fitz doesn't have a table API; cells are rectangles).
    rows = 6
    cols = 4
    col_w = (page_w - 100) / cols
    row_h = 36
    table_top = 140
    headers = ["Quarter", "Revenue", "Costs", "Margin"]
    for c, label in enumerate(headers):
        x0 = 50 + c * col_w
        p.draw_rect(fitz.Rect(x0, table_top, x0 + col_w, table_top + row_h),
                    color=(0.4, 0.4, 0.55), fill=(0.4, 0.4, 0.55), width=0)
        p.insert_text((x0 + 8, table_top + 22), label,
                      fontname="hebo", fontsize=11, color=(1, 1, 1))
    for r in range(1, rows):
        for c in range(cols):
            x0 = 50 + c * col_w
            y0 = table_top + r * row_h
            fill = (0.18, 0.18, 0.25) if r % 2 == 0 else (0.15, 0.15, 0.2)
            p.draw_rect(fitz.Rect(x0, y0, x0 + col_w, y0 + row_h),
                        color=fill, fill=fill, width=0)
            label = ["Q1", "Q2", "Q3", "Q4", "FY"][r - 1] if c == 0 else \
                    f"${r*1234 + c*100:,}"
            p.insert_text((x0 + 8, y0 + 22), label,
                          fontname=FONT_REG, fontsize=11,
                          color=(0.95, 0.95, 0.95))

    return doc


def add_outline(doc: fitz.Document) -> None:
    """Attach a chapter/section outline so the TOC sidebar has content."""
    toc = [
        [1, "Title Page",                     1],
        [1, "Chapter 1 — Overview",           2],
        [1, "Chapter 2 — Embedded Image",     3],
        [1, "Chapter 3 — Contents",           4],
        [2, "Section A",                      4],
        [2, "Section B",                      4],
        [1, "Chapter 4 — Sample Table",       5],
    ]
    doc.set_toc(toc)


def main() -> int:
    ASSET_DIR.mkdir(parents=True, exist_ok=True)
    doc = build()
    add_outline(doc)
    doc.save(str(OUT_PDF), garbage=4, deflate=True)
    doc.close()

    # Verify and write manifest.
    reopened = fitz.open(str(OUT_PDF))
    manifest = {
        "pdf": str(OUT_PDF.relative_to(PROJECT_ROOT)),
        "page_count": len(reopened),
        "pages": [
            {"index": i, "title": p.get_text()[:60].strip() or "(raster)"}
            for i, p in enumerate(reopened)
        ],
        "outline": reopened.get_toc(),
    }
    MANIFEST.write_text(json.dumps(manifest, indent=2))
    reopened.close()

    print(f"Wrote {OUT_PDF} ({OUT_PDF.stat().st_size:,} bytes, "
          f"{manifest['page_count']} pages)")
    print(f"Outline entries: {len(manifest['outline'])}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
